#!/bin/bash

# This script is meant to cheange the System Color Theme in a Linux+Hyprland setup
# This script is using the Catppuccin palette as reference
# It will have a preset of 3 Colors: Green+Yellow, Blue+Purple, Red+Orange
# It will affect the following:
# - GTK Theme
# - Icon Theme
# - Waybar Colors
# - Tofi Colors
# - FiSH Colors
# - Hyprland Border Colors
# - SWWW Background Image (from set of 3)

# Check if $THEME_SWITCHER is set
# If not, set it to 0
if [ -z "$THEME_SWITCHER" ]; then
    THEME_SWITCHER="green+yellow"
elif [ $THEME_SWITCHER -eq "red+orange" ]; then
    THEME_SWITCHER="green+yellow"
else
    THEME_SWITCHER="blue+purple"
fi

# in the .local/share/theme-switcher/themes.json file, the following is stored:
# {
#   "green+yellow": {
#     "gtk": "catppuccin-mocha-green-standard+default",
#     "icon": "Reversal-green-dark",
#     "waybar": [
#       "#a6e3a1",
#       "#f9e2af"
#     ],
#     "tofi": "#a6e3a1",
#     "fish": "166;227;Border 161",
#     "hyprland": [
#       "#a6e3a1",
#       "#f9e2af"
#     ],
#     "swww": "green"
#   },
#   "blue+purple": {
#     "gtk": "catppuccin-mocha-blue-standard+default",
#     "icon": "Papirus-Dark",
#     "waybar": [
#       "#89b4fa",
#       "#cba6f7"
#     ],
#     "tofi": "#89b4fa",
#     "fish": "137;180;250",
#     "hyprland": [
#       "#89b4fa",
#       "#cba6f7"
#     ],
#     "swww": "blue"
#   },
#   "red+orange": {
#     "gtk": "catppuccin-mocha-blue-standard+default",
#     "icon": "Papirus-Dark",
#     "waybar": [
#       "#f38ba8",
#       "#fab387"
#     ],
#     "tofi": "#f38ba8",
#     "fish": "#fab387",
#     "hyprland": [
#       "#f38ba8",
#       "#fab387"
#     ],
#     "swww": "red"
#   }
# }

# Set the theme based on the $THEME_SWITCHER value
case $THEME_SWITCHER in
    "green+yellow")
        # Green+Yellow
        # GTK Theme
        sed -i "s|gtk-theme=.*|gtk-theme=$(cat ~/.local/share/theme-switcher/themes.json | jq -r '.["green+yellow"].gtk')|g" ~/.local/share/nwg-look/gsettings
        # Icon Theme

        # Waybar Colors
        #sed -i 's/#a6e3a1/#a6e3a1/g' ~/.config/waybar/config
        #sed -i 's/#f9e2af/#f9e2af/g' ~/.config/waybar/config
        # Tofi Colors
        sed -i 's/#a6e3a1/#a6e3a1/g' ~/.config/tofi/config
        # FiSH Colors
        sed -i 's/166;227;Border 161/166;227;Border 161/g' ~/.config/fish/config
        # Hyprland Border Colors
        sed -i 's/#a6e3a1/#a6e3a1/g' ~/.config/hyprland/config
        sed -i 's/#f9e2af/#f9e2af/g' ~/.config/hyprland/config
        # SWWW Background Image
        gsettings set org.gnome.desktop.background picture-uri "file:///home/username/.local/share/theme-switcher/swww/green.jpg"
        ;;
    "blue+purple")
        # Blue+Purple
        # GTK Theme
        gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-mocha-blue-standard+default"
        # Icon Theme
        gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
        # Waybar Colors
        #sed -i 's/#a6e3a1/#89b4fa/g' ~/.config/waybar/config
        #sed -i 's/#f9e2af/#cba6f7/g' ~/.config/waybar/config
        # Tofi Colors
        sed -i 's/#a6e3a1/#89b4fa/g' ~/.config/tofi/config
        # FiSH Colors
        sed -i 's/166;227;Border 161/137;180;250/g' ~/.config/fish/config
        # Hyprland Border Colors
